name: first-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"

      - name: Get branch name 1
        run: echo "Branch name is ${{ github.ref }}"

      - name: Get branch name 2
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: echo "Branch name is ${{ env.BRANCH_NAME }}"

      - name: Print goodbye
        run: echo "Done - bye!"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Git log
        run: git log --oneline

      - name: Get previous commit
        id: prev-commit
        run: echo "prev_commit=$(git rev-parse HEAD^1)" >> $GITHUB_OUTPUT

      - name: Output from previous step
        run: echo "${{ steps.prev-commit.outputs.prev_commit }}"

      - name: Compare file contents
        id: compare
        run: |
          git show ${{ steps.prev-commit.outputs.prev_commit }}:file.txt
          cat file.txt
